stages:
  - uhd
  - gnuradio
  - fpga

.conditionals: &conditionals
  refs:
    - master
    - merge_requests
    - web

.uhd-build: &uhd-build
  - mkdir build
  - cd build
  - cmake ../ -DENABLE_UHD=1 -DENABLE_GNURADIO=0
  - make -j10

.gnuradio-build: &gnuradio-build
  - mkdir build
  - cd build
  - cmake ../ -DENABLE_UHD=1 -DENABLE_GNURADIO=1
  - make -j10

build-uhd-master:
  stage: uhd
  image: registry.gitlab.com/ejk/rf-community-docker/uhd:master-rfnoc-all
  script: *uhd-build
  only: *conditionals

build-uhd-3.13:
  stage: uhd
  image: registry.gitlab.com/ejk/rf-community-docker/uhd:UHD-3.13-rfnoc-all
  script: *uhd-build
  only: *conditionals

build-gnuradio-maint-uhd-master:
  stage: gnuradio
  image: registry.gitlab.com/ejk/rf-community-docker/gnuradio:maint-3.7-UHD-master-rfnoc
  script: *gnuradio-build
  only: *conditionals

build-gnuradio-maint-uhd-3.13:
  stage: gnuradio
  image: registry.gitlab.com/ejk/rf-community-docker/gnuradio:maint-3.7-UHD-3.13-rfnoc
  script: *gnuradio-build
  only: *conditionals

fpga-test:
  stage: fpga
  script:
    - echo Hello World
  only:
    - master
    - branches
    - merge_requests
    - web
