stages:
  - build
  - fpga

job-build-uhd-v3.13.0.1:
  stage: build
  image: registry.gitlab.com/ejk/rf-community-cores/uhd-rfnoc:v3.13.0.1
  script:
    - mkdir build
    - cd build
    - cmake ../ -DENABLE_UHD=1 -DENABLE_GNURADIO=0
    - make -j10
  only:
    - master
    - merge_requests
    - web

job-fpga-test:
  stage: fpga
  script:
    - echo Hello World
  only:
    - master
    - merge_requests
    - web
